### ISSUE TITLE
Comparator energy reference

### ISSUE THREAD

**Issue by suyashbakshi** [Accelergy-Project/accelergy-aladdin-plug-in#5]
Hello @nellie-wu,
Is the comparator energy values reported [here](https://github.com/Accelergy-Project/accelergy-aladdin-plug-in/blob/6a9115152b96a5f616d518289be8dce0c81c2757/data/comparator.csv#L1) for per-bit comparison energy? I understand that it is reported for 32-bit comparator.
However, my confusion stems from the fact that the several references I found for comparator circuits report ~40 fJ for a 1-bit comparators used in ADCs. For example:
- https://ieeexplore.ieee.org/document/8094528
- https://ieeexplore.ieee.org/document/8710619
and several others.

It would be helpful if you could clarify this, and if possible, provide the reference for the comparator energy numbers.

Thanks

**Comment by tanner-andrulis** [comment]
These numbers are for a 32-bit comparison with a 32-bit digital comparator, referencing https://github.com/harvard-acc/ALADDIN. 

It is a very different circuit than an analog comparator that would be used in an ADC, hence there should be no expectation that the numbers are the same as in these references.

Nellie has graduated, so I apologize but I can not get you any more detail on where exactly the numbers came from in https://github.com/harvard-acc/ALADDIN. If you'd like to investigate further, I'd recommend implementing the comparators in ALADDIN and seeing what energy/area numbers come out.
